export const Data = [
    {
        id: 1,
        question: 'Which statement about Hooks is not true?',
        answer_a:
            'Hooks are 100% backwards-compatible and can be used side by side with classes',
        answer_b: 'Hooks are still in beta and not available yet',
        answer_c:
            "Hooks are completely opt-in, there's no need to rewrite existing code",
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 2,
        question: 'Which one is not a Hook?',
        answer_a: 'useState()',
        answer_b: 'useConst()',
        answer_c: 'useReducer()',
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 3,
        question: 'What Hook should be used for data fetching?',
        answer_a: 'useDataFetching()',
        answer_b: 'useApi()',
        answer_c: 'useEffect()',
        answer_d: 'useRequest()',
        correct_answer: 'c',
    },
    {
        id: 4,
        question: 'Which statement about Hooks is not true?',
        answer_a:
            'Hooks are 100% backwards-compatible and can be used side by side with classes',
        answer_b: 'Hooks are still in beta and not available yet',
        answer_c:
            "Hooks are completely opt-in, there's no need to rewrite existing code",
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 5,
        question: 'Which one is not a Hook?',
        answer_a: 'useState()',
        answer_b: 'useConst()',
        answer_c: 'useReducer()',
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 6,
        question: 'What Hook should be used for data fetching?',
        answer_a: 'useDataFetching()',
        answer_b: 'useApi()',
        answer_c: 'useEffect()',
        answer_d: 'useRequest()',
        correct_answer: 'c',
    },
    {
        id: 7,
        question: 'Which statement about Hooks is not true?',
        answer_a:
            'Hooks are 100% backwards-compatible and can be used side by side with classes',
        answer_b: 'Hooks are still in beta and not available yet',
        answer_c:
            "Hooks are completely opt-in, there's no need to rewrite existing code",
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 8,
        question: 'Which one is not a Hook?',
        answer_a: 'useState()',
        answer_b: 'useConst()',
        answer_c: 'useReducer()',
        answer_d: 'All of the above',
        correct_answer: 'b',
    },
    {
        id: 9,
        question: 'What Hook should be used for data fetching?',
        answer_a: 'useDataFetching()',
        answer_b: 'useApi()',
        answer_c: 'useEffect()',
        answer_d: 'useRequest()',
        correct_answer: 'c',
    },
    {
        id: 10,
        question: 'What Hook should be used for data fetching?',
        answer_a: 'useDataFetching()',
        answer_b: 'useApi()',
        answer_c: 'useEffect()',
        answer_d: 'useRequest()',
        correct_answer: 'c',
    },
];